# Generated by Django 5.2.7 on 2026-09-17 04:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='School Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Slug')),
                ('code', models.CharField(db_index=True, help_text='Short alphanumeric identifier, e.g. LSM-01', max_length=32, unique=True, verbose_name='School Code')),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='School Logo URL')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Contact Email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Contact Phone')),
                ('address', models.TextField(blank=True, verbose_name='Physical Address')),
                ('timezone', models.CharField(default='UTC', max_length=64, verbose_name='Timezone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=100, verbose_name='Setting Key')),
                ('value', models.JSONField(default=dict, verbose_name='Setting Value')),
            ],
            options={
                'verbose_name': 'School Setting',
                'verbose_name_plural': 'School Settings',
                'db_table': 'school_settings',
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. 2026-2027', max_length=64, verbose_name='Academic Year Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_current', models.BooleanField(default=False, verbose_name='Is Current Academic Year')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='schools.school')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'db_table': 'academic_years',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin (Global)'), ('SCHOOL_ADMIN', 'School Admin / Principal'), ('TEACHER', 'Teacher / Educator'), ('PARENT', 'Parent / Guardian'), ('CHILD', 'Child / Kid Mode')], db_index=True, max_length=32, verbose_name='Role')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default School Context')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='schools.school')),
            ],
            options={
                'verbose_name': 'School Membership',
                'verbose_name_plural': 'School Memberships',
                'db_table': 'school_memberships',
                'ordering': ['-is_default', 'school__name'],
            },
        ),
    ]
