# Generated by Django 5.2.7 on 2026-09-17 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='schools.school'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_school_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='schoolmembership',
            constraint=models.UniqueConstraint(fields=('user', 'school', 'role'), name='unique_user_school_role'),
        ),
        migrations.AddConstraint(
            model_name='schoolsetting',
            constraint=models.UniqueConstraint(fields=('school', 'key'), name='unique_school_setting_key'),
        ),
    ]
