# Generated by Django 5.2.7 on 2026-09-17 05:06

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Announcement Title')),
                ('message', models.TextField(verbose_name='Message Body')),
                ('audience_type', models.CharField(choices=[('ALL_SCHOOL', 'Whole School (All Parents & Staff)'), ('CLASS_LEVEL', 'Specific Grade Level'), ('SECTION', 'Specific Classroom Section'), ('INDIVIDUAL_CHILD', 'Specific Child / Family Notice')], db_index=True, default='ALL_SCHOOL', max_length=20, verbose_name='Audience Scope')),
                ('publish_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Publish Date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Pin to Top')),
                ('priority', models.CharField(choices=[('LOW', 'Low / Information'), ('NORMAL', 'Normal / General'), ('HIGH', 'Important'), ('URGENT', 'Urgent / Emergency')], default='NORMAL', max_length=20, verbose_name='Priority Level')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'db_table': 'announcements',
                'ordering': ['-is_pinned', '-publish_date', '-created_at'],
            },
        ),
    ]
