[pytest]
DJANGO_SETTINGS_MODULE = config.settings.development
python_files = test_*.py *_test.py tests.py
addopts = --tb=short -ra -v
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
