# Generated by Django 5.1.15 on 2026-09-18 07:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0002_initial"),
        ("learning", "0001_initial"),
        ("schools", "0002_initial"),
        ("students", "0002_alter_child_admission_date_alter_pickuprecord_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_learning_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activity",
            name="template_category",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="activity",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Child-facing quest instructions",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy (Level 1)"),
                            ("MEDIUM", "Medium (Level 2)"),
                            ("HARD", "Challenging (Level 3)"),
                        ],
                        default="EASY",
                        max_length=20,
                    ),
                ),
                ("estimated_duration_minutes", models.PositiveIntegerField(default=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_template", models.BooleanField(default=False)),
                (
                    "cover_image_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("theme_color", models.CharField(default="sky", max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_homework_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "learning_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homework_sets",
                        to="learning.learningarea",
                    ),
                ),
                (
                    "learning_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_sets",
                        to="learning.learninglevel",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_sets",
                        to="schools.school",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homework_sets",
                        to="learning.learningtopic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homework Set",
                "verbose_name_plural": "Homework Sets",
                "db_table": "learning_homework",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="activityattempt",
            name="homework",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to="learning.homework",
            ),
        ),
        migrations.CreateModel(
            name="HomeworkAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("CLASS", "Whole Class Level"),
                            ("SECTION", "Specific Classroom Section"),
                            ("INDIVIDUAL_CHILDREN", "Selected Children"),
                        ],
                        default="SECTION",
                        max_length=30,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        db_index=True,
                        default="PUBLISHED",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("teacher_notes", models.TextField(blank=True, default="")),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_homework_list",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "class_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homework_assignments",
                        to="classes.classlevel",
                    ),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="learning.homework",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_assignments",
                        to="schools.school",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="homework_assignments",
                        to="classes.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homework Assignment",
                "verbose_name_plural": "Homework Assignments",
                "db_table": "learning_homework_assignments",
                "ordering": ["-assigned_at", "-due_date"],
            },
        ),
        migrations.AddField(
            model_name="activityattempt",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to="learning.homeworkassignment",
            ),
        ),
        migrations.CreateModel(
            name="HomeworkActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_index", models.PositiveIntegerField(default=1)),
                ("instructions_override", models.TextField(blank=True, default="")),
                ("required_to_complete", models.BooleanField(default=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_inclusions",
                        to="learning.activity",
                    ),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="learning.homework",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homework Activity",
                "verbose_name_plural": "Homework Activities",
                "db_table": "learning_homework_activities",
                "ordering": ["order_index"],
                "unique_together": {("homework", "activity")},
            },
        ),
        migrations.CreateModel(
            name="ChildHomeworkProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("OVERDUE", "Overdue"),
                        ],
                        db_index=True,
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_activities_count", models.PositiveIntegerField(default=0)),
                ("total_activities_count", models.PositiveIntegerField(default=1)),
                ("total_stars_earned", models.PositiveIntegerField(default=0)),
                ("average_score", models.PositiveIntegerField(default=0)),
                ("teacher_feedback", models.TextField(blank=True, default="")),
                ("teacher_feedback_at", models.DateTimeField(blank=True, null=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_progress_set",
                        to="students.child",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_homework_progress_set",
                        to="schools.school",
                    ),
                ),
                (
                    "teacher_feedback_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="given_homework_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="learning.homeworkassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Child Homework Progress",
                "verbose_name_plural": "Child Homework Progress Records",
                "db_table": "learning_child_homework_progress",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["child", "status"],
                        name="learning_ch_child_i_0607fa_idx",
                    ),
                    models.Index(
                        fields=["assignment", "status"],
                        name="learning_ch_assignm_525de5_idx",
                    ),
                ],
                "unique_together": {("assignment", "child")},
            },
        ),
    ]
