# Generated by Django 5.2.7 on 2026-09-26 14:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0002_initial"),
        ("students", "0002_alter_child_admission_date_alter_pickuprecord_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentPurpose",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="Purpose Code",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Purpose Name")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CORE_EDUCATION", "Core Educational Service & Enrollment"),
                            (
                                "SAFETY_HEALTH",
                                "Child Safety, Emergency & Medical Records",
                            ),
                            (
                                "ATTENDANCE_DISMISSAL",
                                "Daily Attendance & Secure Dismissal PINs",
                            ),
                            ("MEDIA_MOMENTS", "Classroom Moments & Photo Sharing"),
                            ("COMMUNICATION", "School Bulletins & Direct Messaging"),
                            (
                                "LEARNING_ANALYTICS",
                                "Developmental Milestone & Learning Progress",
                            ),
                            ("PAYMENTS", "Fee Billing & Transaction Receipts"),
                        ],
                        default="CORE_EDUCATION",
                        max_length=32,
                        verbose_name="Category",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "data_fields_collected",
                    models.JSONField(
                        default=list,
                        help_text="List of specific field names",
                        verbose_name="Data Fields Covered",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False, verbose_name="Mandatory for Core Service"
                    ),
                ),
                (
                    "default_granted",
                    models.BooleanField(
                        default=False,
                        verbose_name="Default Status (Opt-in by default for optional items)",
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Display Order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active Purpose"),
                ),
            ],
            options={
                "verbose_name": "Consent Purpose",
                "verbose_name_plural": "Consent Purposes",
                "db_table": "privacy_consent_purposes",
                "ordering": ["order_index", "name"],
            },
        ),
        migrations.CreateModel(
            name="DataRetentionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "data_category",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Data Category",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(max_length=150, verbose_name="Display Name"),
                ),
                (
                    "purpose",
                    models.CharField(max_length=200, verbose_name="Processing Purpose"),
                ),
                (
                    "retention_period_days",
                    models.PositiveIntegerField(
                        default=365, verbose_name="Retention Period (Days)"
                    ),
                ),
                (
                    "statutory_justification",
                    models.TextField(verbose_name="Legal / Statutory Justification"),
                ),
                (
                    "deletion_method",
                    models.CharField(
                        choices=[
                            (
                                "HARD_DELETE",
                                "Permanent Hard Deletion from Database & Storage",
                            ),
                            (
                                "ANONYMIZE",
                                "Irreversible Pseudonymization & De-identification",
                            ),
                            (
                                "ARCHIVE_PURGE",
                                "Encrypted Archival for Statutory Accounting / Tax Audit",
                            ),
                        ],
                        default="HARD_DELETE",
                        max_length=20,
                        verbose_name="Deletion Method",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active Policy"),
                ),
            ],
            options={
                "verbose_name": "Data Retention Policy",
                "verbose_name_plural": "Data Retention Policies",
                "db_table": "privacy_retention_policies",
                "ordering": ["data_category"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyNotice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. v1.0-2026",
                        max_length=32,
                        unique=True,
                        verbose_name="Notice Version",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="EduKadence Privacy Notice & Data Governance Statement",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Effective Date",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        help_text="Clear, plain-language summary for parents and staff",
                        verbose_name="Executive Summary",
                    ),
                ),
                (
                    "itemized_purposes",
                    models.JSONField(
                        default=list,
                        help_text="List of objects: {purpose_code, purpose_name, description, data_fields, legal_basis, retention_period, third_party_processors}",
                        verbose_name="Itemized Processing Purposes & Data Categories",
                    ),
                ),
                (
                    "child_safeguards_statement",
                    models.TextField(
                        default="EduKadence provides an ad-free, secure learning environment for children aged 2-10. We strictly prohibit tracking, behavioural profiling, and targeted advertising directed at children.",
                        verbose_name="Child Data Protection Statement",
                    ),
                ),
                (
                    "grievance_officer_name",
                    models.CharField(
                        default="Data Protection & Grievance Officer",
                        max_length=120,
                        verbose_name="Grievance Redressal Officer",
                    ),
                ),
                (
                    "grievance_officer_email",
                    models.EmailField(
                        default="privacy@edukadence.com",
                        max_length=255,
                        verbose_name="Grievance Email",
                    ),
                ),
                (
                    "grievance_officer_phone",
                    models.CharField(
                        default="+91 1800-EDU-PRIVACY",
                        max_length=32,
                        verbose_name="Grievance Phone",
                    ),
                ),
                (
                    "grievance_officer_address",
                    models.TextField(
                        default="EduKadence Data Governance Cell, India",
                        verbose_name="Physical Address",
                    ),
                ),
                (
                    "dpo_applicable",
                    models.BooleanField(
                        default=False,
                        verbose_name="Significant Data Fiduciary DPO Configured",
                    ),
                ),
                (
                    "dpo_name",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Data Protection Officer Name",
                    ),
                ),
                (
                    "dpo_email",
                    models.EmailField(
                        blank=True, max_length=255, verbose_name="DPO Email"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        verbose_name="Is Currently Active Notice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Privacy Notice",
                "verbose_name_plural": "Privacy Notices",
                "db_table": "privacy_notices",
                "ordering": ["-effective_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataBreachIncident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incident_number",
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        verbose_name="Incident Number",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Incident Title"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Nature and Scope of Incident"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low (Minimal Risk, Promptly Contained)"),
                            ("MEDIUM", "Medium (Limited Personal Data Affected)"),
                            (
                                "HIGH",
                                "High (Significant Potential Impact on Principals)",
                            ),
                            (
                                "CRITICAL",
                                "Critical (Large-Scale or Severe High-Risk Personal Data)",
                            ),
                        ],
                        default="LOW",
                        max_length=20,
                        verbose_name="Severity Level",
                    ),
                ),
                (
                    "affected_categories",
                    models.JSONField(
                        default=list,
                        help_text="e.g. [Student Profile, Attendance, Parent Phone]",
                        verbose_name="Affected Data Categories",
                    ),
                ),
                (
                    "estimated_affected_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Estimated Affected Principals"
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Detected Timestamp",
                    ),
                ),
                (
                    "contained_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Contained Timestamp"
                    ),
                ),
                (
                    "dpbi_status",
                    models.CharField(
                        choices=[
                            (
                                "NOT_REQUIRED",
                                "Board Notification Not Required / Exempt",
                            ),
                            ("PREPARING", "Preparing DPBI Form / Triage"),
                            (
                                "NOTIFIED_BOARD",
                                "Formally Reported to Data Protection Board of India",
                            ),
                        ],
                        default="NOT_REQUIRED",
                        max_length=20,
                        verbose_name="DPBI Notification Status",
                    ),
                ),
                (
                    "dpbi_notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="DPBI Notified Timestamp"
                    ),
                ),
                (
                    "principals_status",
                    models.CharField(
                        choices=[
                            (
                                "NOT_REQUIRED",
                                "Principal Notification Not Required (No Harm Risk)",
                            ),
                            ("SCHEDULED", "Notification Scheduled"),
                            (
                                "NOTIFIED_USERS",
                                "Affected Data Principals Promptly Notified",
                            ),
                        ],
                        default="NOT_REQUIRED",
                        max_length=20,
                        verbose_name="Data Principals Notification Status",
                    ),
                ),
                (
                    "principals_notified_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Principals Notified Timestamp",
                    ),
                ),
                (
                    "containment_measures",
                    models.TextField(
                        blank=True,
                        verbose_name="Containment & Remediation Actions Taken",
                    ),
                ),
                (
                    "post_incident_review",
                    models.TextField(
                        blank=True,
                        verbose_name="Post-Incident Review & Root Cause Analysis",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific school tenant or NULL if global platform incident",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breach_incidents",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Breach Incident",
                "verbose_name_plural": "Data Breach Incidents",
                "db_table": "privacy_breach_incidents",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="DataPrincipalNomination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nominee_name",
                    models.CharField(max_length=150, verbose_name="Nominee Full Name"),
                ),
                (
                    "nominee_relationship",
                    models.CharField(
                        help_text="e.g. Spouse, Sibling, Legal Counsel, Guardian",
                        max_length=80,
                        verbose_name="Relationship to Data Principal",
                    ),
                ),
                (
                    "nominee_phone",
                    models.CharField(
                        max_length=32, verbose_name="Nominee Phone Number"
                    ),
                ),
                (
                    "nominee_email",
                    models.EmailField(
                        max_length=255, verbose_name="Nominee Email Address"
                    ),
                ),
                (
                    "nominee_address",
                    models.TextField(blank=True, verbose_name="Nominee Address"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active Nomination"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Special Instructions / Conditions"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_nominations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Principal Nomination",
                "verbose_name_plural": "Data Principal Nominations",
                "db_table": "privacy_nominations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataPrincipalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference_number",
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        verbose_name="Reference Number",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            (
                                "ACCESS_SUMMARY",
                                "Right to Access Summary & Processing Details (Sec 11)",
                            ),
                            (
                                "CORRECTION",
                                "Right to Correction of Inaccurate Data (Sec 12)",
                            ),
                            (
                                "COMPLETION",
                                "Right to Completion of Incomplete Data (Sec 12)",
                            ),
                            ("UPDATING", "Right to Updating Out-of-Date Data (Sec 12)"),
                            (
                                "ERASURE",
                                "Right to Erasure / Account & Data Deletion (Sec 12)",
                            ),
                            (
                                "PROCESSING_INQUIRY",
                                "Inquiry on Third-Party Data Processors & Sharing (Sec 11(1)(b))",
                            ),
                        ],
                        db_index=True,
                        default="ACCESS_SUMMARY",
                        max_length=32,
                        verbose_name="Request Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted & Acknowledged"),
                            ("IDENTITY_VERIFIED", "Identity Verified"),
                            ("UNDER_REVIEW", "Under Review by School Privacy Team"),
                            ("PROCESSING", "Processing & Data Compilation in Progress"),
                            ("COMPLETED", "Completed & Delivered"),
                            ("REJECTED", "Rejected with Lawful Justification"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "details",
                    models.TextField(verbose_name="Request Description / Specifics"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Submitted At"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Acknowledged At"
                    ),
                ),
                (
                    "deadline_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Statutory Deadline"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True,
                        verbose_name="Resolution Notes / Decision Justification",
                    ),
                ),
                (
                    "result_package",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Compiled Data Package"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_privacy_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: When parent is exercising rights on behalf of their child",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_requests",
                        to="students.child",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Principal Request",
                "verbose_name_plural": "Data Principal Requests",
                "db_table": "privacy_data_requests",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CONSENT_GRANTED", "Consent Granted"),
                            ("CONSENT_WITHDRAWN", "Consent Withdrawn"),
                            (
                                "RIGHTS_REQUEST_SUBMITTED",
                                "Data Principal Request Submitted",
                            ),
                            (
                                "RIGHTS_REQUEST_COMPLETED",
                                "Data Principal Request Completed",
                            ),
                            (
                                "DATA_EXPORT_DOWNLOADED",
                                "Data Principal Export Generated/Downloaded",
                            ),
                            ("DATA_ERASURE_EXECUTED", "Data Erasure Executed"),
                            ("GRIEVANCE_SUBMITTED", "Privacy Grievance Submitted"),
                            ("GRIEVANCE_RESOLVED", "Privacy Grievance Resolved"),
                            ("BREACH_LOGGED", "Breach Incident Logged"),
                            (
                                "RETENTION_CLEANUP_RUN",
                                "Retention Cleanup Task Executed",
                            ),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Action",
                    ),
                ),
                (
                    "target_resource",
                    models.CharField(
                        max_length=150, verbose_name="Target Resource / Entity"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Event Metadata (Sanitized)",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Timestamp",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="privacy_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="privacy_audit_logs",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Privacy Audit Log",
                "verbose_name_plural": "Privacy Audit Logs",
                "db_table": "privacy_audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyGrievance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grievance_number",
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        unique=True,
                        verbose_name="Grievance Number",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "UNAUTHORIZED_PROCESSING",
                                "Unauthorized or Excessive Data Processing",
                            ),
                            (
                                "CONSENT_VIOLATION",
                                "Consent Not Respected / Withdrawal Ignored",
                            ),
                            (
                                "RIGHTS_NON_COMPLIANCE",
                                "Failure to Fulfill Data Access / Correction / Erasure",
                            ),
                            (
                                "CHILD_DATA_PROTECTION",
                                "Child Safety & Protection Concern",
                            ),
                            (
                                "SECURITY_BREACH_SUSPICION",
                                "Suspected Data Leak or Security Incident",
                            ),
                            (
                                "ACCURACY_COMPLETION",
                                "Inaccurate or Misleading Personal Data",
                            ),
                            ("OTHER", "General Privacy Grievance"),
                        ],
                        db_index=True,
                        default="UNAUTHORIZED_PROCESSING",
                        max_length=32,
                        verbose_name="Category",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        max_length=200, verbose_name="Subject / Brief Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Detailed Description of Grievance"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Grievance Received & Registered"),
                            (
                                "UNDER_INVESTIGATION",
                                "Under Investigation by Grievance Officer",
                            ),
                            ("ACTION_TAKEN", "Corrective Action Taken"),
                            ("RESOLVED", "Resolved & Formally Closed"),
                            ("REJECTED", "Closed / Unsubstantiated"),
                        ],
                        db_index=True,
                        default="RECEIVED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Submitted At"
                    ),
                ),
                (
                    "target_resolution_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Statutory Resolution Deadline (Max 90 days)",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "resolution_summary",
                    models.TextField(
                        blank=True,
                        verbose_name="Resolution Summary & Remedial Action Report",
                    ),
                ),
                (
                    "assigned_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_grievances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_grievances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Privacy Grievance",
                "verbose_name_plural": "Privacy Grievances",
                "db_table": "privacy_grievances",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GRANTED", "Consent Granted"),
                            ("WITHDRAWN", "Consent Withdrawn"),
                            ("DENIED", "Consent Denied / Refused"),
                        ],
                        db_index=True,
                        default="GRANTED",
                        max_length=20,
                        verbose_name="Consent Status",
                    ),
                ),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            (
                                "PASSWORD_AUTHENTICATED",
                                "Authenticated Portal Action (Password/Session Verified)",
                            ),
                            ("PORTAL_ACTION", "Direct In-App Toggle"),
                            ("OTP_VERIFIED", "OTP Verified Consent"),
                            ("PARENT_SIGNATURE", "Parental Admission Form Consent"),
                        ],
                        default="PASSWORD_AUTHENTICATED",
                        max_length=32,
                        verbose_name="Verification Method",
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Granted Timestamp",
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Withdrawn Timestamp"
                    ),
                ),
                (
                    "revocation_reason",
                    models.TextField(
                        blank=True, verbose_name="Withdrawal Reason / Remarks"
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Hashed IP / Origin Context",
                    ),
                ),
                (
                    "user_agent_min",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Client Context"
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Child for whom verifiable parental consent is recorded",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_consents",
                        to="students.child",
                    ),
                ),
                (
                    "purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="privacy.consentpurpose",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_set",
                        to="schools.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Data Principal giving the consent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consent_records",
                        to="privacy.privacynotice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent Record",
                "verbose_name_plural": "Consent Records",
                "db_table": "privacy_consent_records",
                "ordering": ["-granted_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "purpose", "status"],
                        name="privacy_con_user_id_6bee7b_idx",
                    ),
                    models.Index(
                        fields=["child", "purpose", "status"],
                        name="privacy_con_child_i_b7307e_idx",
                    ),
                ],
            },
        ),
    ]
