import React, { useState } from 'react';
import { useAuth } from '../hooks/useAuth';
import { useToast } from '../hooks/useToast';
import {
  Building2,
  Calendar,
  Sliders,
  Palette,
  CheckCircle2,
  ShieldAlert,
} from 'lucide-react';
import {
  PageHeader,
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardBody,
  Input,
  Select,
  Toggle,
  Button,
  Tabs,
} from '../components/ui';

export const SettingsPage = () => {
  const { activeMembership } = useAuth();
  const toast = useToast();

  const [schoolName, setSchoolName] = useState(activeMembership?.school_name || 'Little Sprouts Montessori');
  const [schoolCode, setSchoolCode] = useState(activeMembership?.school_code || 'LSM-01');
  const [timezone, setTimezone] = useState('America/New_York');
  const [kidModeEnabled, setKidModeEnabled] = useState(true);
  const [parentPortalEnabled, setParentPortalEnabled] = useState(true);
  const [isSaving, setIsSaving] = useState(false);

  const handleSave = () => {
    setIsSaving(true);
    setTimeout(() => {
      setIsSaving(false);
      toast.success('School settings updated successfully.');
    }, 600);
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="School Settings & Preferences"
        subtitle={`Configure parameters for ${activeMembership?.school_name || 'Active School'}`}
        breadcrumbs={[
          { label: 'Dashboard', to: '/app' },
          { label: 'Settings' },
        ]}
        action={
          <Button variant="primary" size="sm" onClick={handleSave} isLoading={isSaving}>
            Save Changes
          </Button>
        }
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left 2 Cols: School Profile & Academic Year */}
        <div className="lg:col-span-2 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>School Information</CardTitle>
              <CardDescription>
                Primary identification and operational timezone.
              </CardDescription>
            </CardHeader>
            <CardBody className="space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <Input
                  label="School Name"
                  value={schoolName}
                  onChange={(e) => setSchoolName(e.target.value)}
                  required
                />
                <Input
                  label="School Code"
                  value={schoolCode}
                  onChange={(e) => setSchoolCode(e.target.value)}
                  disabled
                  helperText="Unique tenant code generated by system"
                />
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <Select
                  label="Timezone"
                  value={timezone}
                  onChange={(e) => setTimezone(e.target.value)}
                  options={[
                    { value: 'America/New_York', label: 'America/New_York (EST)' },
                    { value: 'America/Chicago', label: 'America/Chicago (CST)' },
                    { value: 'America/Los_Angeles', label: 'America/Los_Angeles (PST)' },
                    { value: 'UTC', label: 'UTC' },
                  ]}
                />
                <Input
                  label="Contact Email"
                  type="email"
                  defaultValue="hello@littlesprouts.edu"
                />
              </div>
            </CardBody>
          </Card>

          {/* Feature Toggles */}
          <Card>
            <CardHeader>
              <CardTitle>Experience Toggles</CardTitle>
              <CardDescription>
                Enable or disable specialized experiences for your school.
              </CardDescription>
            </CardHeader>
            <CardBody className="space-y-4 divide-y divide-slate-100">
              <div className="pt-2">
                <Toggle
                  label="Kid Mode Learning Playground"
                  description="Enable safe, age-appropriate interactive activities and homework for children."
                  enabled={kidModeEnabled}
                  onChange={setKidModeEnabled}
                />
              </div>
              <div className="pt-4">
                <Toggle
                  label="Parent Mobile Portal"
                  description="Allow parents to check attendance, view daily activity feed, and retrieve pickup PINs."
                  enabled={parentPortalEnabled}
                  onChange={setParentPortalEnabled}
                />
              </div>
            </CardBody>
          </Card>
        </div>

        {/* Right Col: Brand Colors & Tokens */}
        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Brand Design Tokens</CardTitle>
              <CardDescription>Derived from EduKadence logo</CardDescription>
            </CardHeader>
            <CardBody className="space-y-3">
              <div className="flex items-center justify-between p-2.5 rounded-xl border border-slate-100 bg-slate-50">
                <div className="flex items-center gap-2.5">
                  <div className="w-6 h-6 rounded-lg bg-brand-600 shadow-xs" />
                  <div className="text-xs">
                    <span className="font-semibold text-slate-800 block">Electric Brand Blue</span>
                    <span className="text-[10px] text-slate-400 font-mono">#0084D6</span>
                  </div>
                </div>
                <span className="text-[10px] font-semibold text-brand-700 bg-brand-50 px-2 py-0.5 rounded">
                  Primary
                </span>
              </div>

              <div className="flex items-center justify-between p-2.5 rounded-xl border border-slate-100 bg-slate-50">
                <div className="flex items-center gap-2.5">
                  <div className="w-6 h-6 rounded-lg bg-skybrand-500 shadow-xs" />
                  <div className="text-xs">
                    <span className="font-semibold text-slate-800 block">Vibrant Sky Cyan</span>
                    <span className="text-[10px] text-slate-400 font-mono">#00C3FF</span>
                  </div>
                </div>
                <span className="text-[10px] font-semibold text-skybrand-700 bg-skybrand-50 px-2 py-0.5 rounded">
                  Accent
                </span>
              </div>

              <div className="flex items-center justify-between p-2.5 rounded-xl border border-slate-100 bg-slate-50">
                <div className="flex items-center gap-2.5">
                  <div className="w-6 h-6 rounded-lg bg-navy-900 shadow-xs" />
                  <div className="text-xs">
                    <span className="font-semibold text-slate-800 block">Deep Slate Navy</span>
                    <span className="text-[10px] text-slate-400 font-mono">#0A192F</span>
                  </div>
                </div>
                <span className="text-[10px] font-semibold text-slate-700 bg-slate-100 px-2 py-0.5 rounded">
                  Dark Surface
                </span>
              </div>
            </CardBody>
          </Card>
        </div>
      </div>
    </div>
  );
};
