# Generated by Django 5.2.7 on 2026-09-17 05:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Activity Title')),
                ('description', models.TextField(verbose_name='Description / Story')),
                ('activity_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Activity Date')),
                ('category', models.CharField(choices=[('ART', 'Art & Craft'), ('LEARNING', 'Early Literacy & Numeracy'), ('MUSIC', 'Music, Dance & Rhymes'), ('OUTDOOR', 'Outdoor & Physical Play'), ('STORY', 'Storytelling & Circle Time'), ('MEAL', 'Meal & Snack Time'), ('NAP', 'Nap & Quiet Rest'), ('OTHER', 'Special Event / Other')], db_index=True, default='LEARNING', max_length=20, verbose_name='Category')),
                ('media_urls', models.JSONField(blank=True, default=list, verbose_name='Media / Photo URLs')),
                ('video_url', models.URLField(blank=True, max_length=500, verbose_name='Video URL')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published to Parents')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='schools.academicyear')),
            ],
            options={
                'verbose_name': 'Class Activity',
                'verbose_name_plural': 'Class Activities',
                'db_table': 'class_activities',
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
    ]
