# Generated by Django 5.2.7 on 2026-09-17 05:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(db_index=True, max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Middle Name')),
                ('last_name', models.CharField(db_index=True, max_length=100, verbose_name='Last Name')),
                ('preferred_name', models.CharField(blank=True, max_length=100, verbose_name='Preferred / Nickname')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='PREFER_NOT_TO_SAY', max_length=20, verbose_name='Gender')),
                ('admission_number', models.CharField(db_index=True, max_length=64, verbose_name='Admission / Student ID')),
                ('admission_date', models.DateField(default=django.utils.timezone.now, verbose_name='Admission Date')),
                ('profile_photo_url', models.CharField(blank=True, max_length=500, verbose_name='Profile Photo URL')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Enrolled'), ('INACTIVE', 'Inactive / Paused'), ('GRADUATED', 'Graduated / Completed'), ('TRANSFERRED', 'Transferred Out')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Enrollment Status')),
                ('blood_group', models.CharField(blank=True, max_length=10, verbose_name='Blood Group')),
                ('medical_notes', models.TextField(blank=True, verbose_name='Allergies & Medical Notes')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32, verbose_name='Emergency Contact Phone')),
                ('notes', models.TextField(blank=True, verbose_name='Staff Notes')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
                'db_table': 'children',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='AuthorizedPickupPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Full Name')),
                ('relationship', models.CharField(help_text='e.g. Grandfather, Driver, Babysitter', max_length=100, verbose_name='Relationship to Child')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone Number')),
                ('photo_url', models.CharField(blank=True, max_length=500, verbose_name='Photo URL')),
                ('identification_number', models.CharField(blank=True, max_length=64, verbose_name='ID / License Number')),
                ('pickup_pin', models.CharField(blank=True, help_text='4-6 digit numeric dismissal verification code', max_length=8, verbose_name='Secret Pickup PIN')),
                ('is_active', models.BooleanField(default=True, verbose_name='Authorization Active')),
                ('notes', models.TextField(blank=True, verbose_name='Authorization Notes / Restrictions')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_pickups', to='students.child')),
            ],
            options={
                'verbose_name': 'Authorized Pickup Person',
                'verbose_name_plural': 'Authorized Pickup Persons',
                'db_table': 'authorized_pickup_persons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('relationship_type', models.CharField(choices=[('MOTHER', 'Mother'), ('FATHER', 'Father'), ('GUARDIAN', 'Legal Guardian'), ('OTHER', 'Other Family Member')], default='MOTHER', max_length=20, verbose_name='Relationship')),
                ('phone', models.CharField(db_index=True, max_length=32, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Email Address')),
                ('occupation', models.CharField(blank=True, max_length=120, verbose_name='Occupation')),
                ('address', models.TextField(blank=True, verbose_name='Home Address')),
                ('preferred_communication', models.CharField(choices=[('IN_APP', 'In-App Portal'), ('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS Text'), ('EMAIL', 'Email')], default='IN_APP', max_length=20, verbose_name='Preferred Communication')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('user', models.ForeignKey(blank=True, help_text='Associated login account if registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent / Guardian',
                'verbose_name_plural': 'Parents & Guardians',
                'db_table': 'parents',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='ChildParentRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('MOTHER', 'Mother'), ('FATHER', 'Father'), ('GUARDIAN', 'Legal Guardian'), ('OTHER', 'Other Family Member')], default='MOTHER', max_length=20, verbose_name='Relationship')),
                ('is_primary_contact', models.BooleanField(default=False, verbose_name='Primary Emergency Contact')),
                ('is_emergency_contact', models.BooleanField(default=True, verbose_name='Emergency Contact')),
                ('can_pickup', models.BooleanField(default=True, verbose_name='Authorized for Daily Pickup')),
                ('communication_authorized', models.BooleanField(default=True, verbose_name='Authorized for School Notices')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='students.child')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='students.parent')),
            ],
            options={
                'verbose_name': 'Child Parent Relationship',
                'verbose_name_plural': 'Child Parent Relationships',
                'db_table': 'child_parent_relationships',
            },
        ),
        migrations.CreateModel(
            name='PickupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='Dismissal Timestamp')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting in Classroom / Care'), ('READY_FOR_PICKUP', 'Ready at Gate / Waiting Room'), ('PICKED_UP', 'Picked Up & Dismissed')], db_index=True, default='WAITING', max_length=20, verbose_name='Status')),
                ('picked_up_by_name', models.CharField(blank=True, max_length=120, verbose_name='Collector Name')),
                ('picked_up_by_relationship', models.CharField(blank=True, max_length=100, verbose_name='Collector Relationship')),
                ('pin_verified', models.BooleanField(default=False, verbose_name='PIN / Identity Verified')),
                ('notes', models.TextField(blank=True, verbose_name='Dismissal Remarks')),
                ('authorized_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_logs', to='students.authorizedpickupperson')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_records', to='students.child')),
                ('recorded_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_pickups', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'verbose_name': 'Pickup Record',
                'verbose_name_plural': 'Pickup Records',
                'db_table': 'pickup_records',
                'ordering': ['-date', '-pickup_time', 'child__first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='child',
            constraint=models.UniqueConstraint(fields=('school', 'admission_number'), name='unique_school_child_admission_number'),
        ),
        migrations.AddConstraint(
            model_name='childparentrelationship',
            constraint=models.UniqueConstraint(fields=('child', 'parent'), name='unique_child_parent_relationship'),
        ),
        migrations.AddConstraint(
            model_name='pickuprecord',
            constraint=models.UniqueConstraint(fields=('school', 'child', 'date'), name='unique_school_child_daily_pickup'),
        ),
    ]
