# Generated by Django 5.2.7 on 2026-09-17 05:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Admission Date'),
        ),
        migrations.AlterField(
            model_name='pickuprecord',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date'),
        ),
    ]
