# Generated by Django 5.2.7 on 2026-09-17 05:06

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI / QR Code'), ('BANK_TRANSFER', 'Bank Transfer / NEFT'), ('CHEQUE', 'Cheque / DD'), ('CARD', 'Debit / Credit Card'), ('OTHER', 'Other')], default='CASH', max_length=20, verbose_name='Payment Method')),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Reference / Transaction / Cheque No')),
                ('receipt_number', models.CharField(db_index=True, max_length=64, verbose_name='Official Receipt Number')),
                ('notes', models.TextField(blank=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name': 'Fee Payment',
                'verbose_name_plural': 'Fee Payments',
                'db_table': 'fee_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Fee Name')),
                ('fee_type', models.CharField(choices=[('ADMISSION', 'Admission / Registration Fee'), ('TUITION', 'Tuition / Academic Fee'), ('ACTIVITY', 'Activity & Materials Fee'), ('ANNUAL', 'Annual / Development Charges'), ('MEALS', 'Snacks / Meals Fee'), ('TRANSPORT', 'Transport / Bus Fee'), ('OTHER', 'Other Charges')], default='TUITION', max_length=20, verbose_name='Fee Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount (INR/Currency)')),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One-Time Payment'), ('MONTHLY', 'Monthly Recurring'), ('QUARTERLY', 'Quarterly (3 Months)'), ('TERMLY', 'Per Term / Semester'), ('YEARLY', 'Annual Payment')], default='MONTHLY', max_length=20, verbose_name='Billing Frequency')),
                ('due_day', models.PositiveIntegerField(default=10, verbose_name='Due Day of Month')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, verbose_name='Description / Notes')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'db_table': 'fee_structures',
                'ordering': ['academic_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='Fee Item Title')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Original Amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Discount / Concession')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Paid')),
                ('due_date', models.DateField(db_index=True, verbose_name='Due Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid in Full'), ('WAIVED', 'Waived / Scholarship'), ('OVERDUE', 'Overdue')], db_index=True, default='PENDING', max_length=20, verbose_name='Payment Status')),
                ('remarks', models.TextField(blank=True, verbose_name='Notes / Concession Reason')),
            ],
            options={
                'verbose_name': 'Student Fee Due',
                'verbose_name_plural': 'Student Fee Dues',
                'db_table': 'student_fee_items',
                'ordering': ['due_date', 'child__first_name'],
            },
        ),
    ]
