# Generated by Django 5.1.15 on 2026-09-18 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fees", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feepayment",
            name="payment_date",
            field=models.DateField(
                db_index=True,
                default=django.utils.timezone.localdate,
                verbose_name="Payment Date",
            ),
        ),
    ]
